export const ADVANCE = {
  components: [
    {
      label: "Url",
      tableView: true,
      key: "url",
      type: "url",
      input: true,
    },
    {
      label: "Phone Number",
      tableView: true,
      key: "phoneNumber",
      type: "phoneNumber",
      input: true,
    },
    {
      label: "Email",
      tableView: true,
      key: "email",
      type: "email",
      input: true,
    },
    {
      label: "Tags",
      tableView: false,
      key: "tags",
      type: "tags",
      input: true,
    },
    {
      label: "Address",
      tableView: false,
      provider: "nominatim",
      key: "address",
      type: "address",
      input: true,
      components: [
        {
          label: "Address 1",
          tableView: false,
          key: "address1",
          type: "textfield",
          input: true,
          customConditional:
            "show = _.get(instance, 'parent.manualMode', false);",
        },
        {
          label: "Address 2",
          tableView: false,
          key: "address2",
          type: "textfield",
          input: true,
          customConditional:
            "show = _.get(instance, 'parent.manualMode', false);",
        },
        {
          label: "City",
          tableView: false,
          key: "city",
          type: "textfield",
          input: true,
          customConditional:
            "show = _.get(instance, 'parent.manualMode', false);",
        },
        {
          label: "State",
          tableView: false,
          key: "state",
          type: "textfield",
          input: true,
          customConditional:
            "show = _.get(instance, 'parent.manualMode', false);",
        },
        {
          label: "Country",
          tableView: false,
          key: "country",
          type: "textfield",
          input: true,
          customConditional:
            "show = _.get(instance, 'parent.manualMode', false);",
        },
        {
          label: "Zip Code",
          tableView: false,
          key: "zip",
          type: "textfield",
          input: true,
          customConditional:
            "show = _.get(instance, 'parent.manualMode', false);",
        },
      ],
    },
    {
      label: "Date / Time",
      tableView: false,
      enableMinDateInput: false,
      datePicker: {
        disableWeekends: false,
        disableWeekdays: false,
      },
      enableMaxDateInput: false,
      key: "dateTime",
      type: "datetime",
      input: true,
      suffix: '<i ref="icon" class="fa fa-calendar" style=""></i>',
      widget: {
        type: "calendar",
        displayInTimezone: "viewer",
        language: "en",
        useLocaleSettings: false,
        allowInput: true,
        mode: "single",
        enableTime: true,
        noCalendar: false,
        format: "yyyy-MM-dd hh:mm a",
        hourIncrement: 1,
        minuteIncrement: 1,
        time_24hr: false,
        minDate: null,
        disableWeekends: false,
        disableWeekdays: false,
        maxDate: null,
      },
    },
    {
      label: "Day",
      hideInputLabels: false,
      inputsLabelPosition: "top",
      useLocaleSettings: false,
      tableView: false,
      fields: {
        day: {
          hide: false,
        },
        month: {
          hide: false,
        },
        year: {
          hide: false,
        },
      },
      key: "day",
      type: "day",
      input: true,
      defaultValue: "00/00/0000",
    },
    {
      label: "Time",
      tableView: true,
      key: "time",
      type: "time",
      input: true,
      inputMask: "99:99",
    },
    {
      label: "Currency",
      mask: false,
      spellcheck: true,
      tableView: false,
      currency: "USD",
      inputFormat: "plain",
      key: "currency",
      type: "currency",
      input: true,
      delimiter: true,
    },
    {
      label: "Survey",
      tableView: false,
      questions: [
        {
          label: "Eat",
          value: "eat",
        },
        {
          label: "Sleep",
          value: "sleep",
        },
        {
          label: "Code",
          value: "code",
        },
        {
          label: "Repeat",
          value: "repeat",
        },
      ],
      values: [
        {
          label: "Morning",
          value: "morning",
        },
        {
          label: "Evening",
          value: "evening",
        },
        {
          label: "Night",
          value: "night",
        },
      ],
      key: "survey",
      type: "survey",
      input: true,
      defaultValue: {
        eat: "morning",
        sleep: "evening",
        code: "night",
        repeat: "evening",
      },
    },
    {
      label: "Signature",
      tableView: false,
      key: "signature",
      type: "signature",
      input: true,
    },
    {
      type: "button",
      label: "Submit",
      key: "submit",
      disableOnInvalid: true,
      input: true,
      tableView: false,
    },
  ],
};
export const BASIC_MORE = {
  components: [
    {
      label: "Name",
      placeholder: "your name",
      description: "Please enter your name",
      tooltip: "Seriously just put your name",
      prefix: "syl",
      suffix: "yte",
      autofocus: true,
      tableView: true,
      validate: {
        required: true,
      },
      key: "sylname",
      type: "textfield",
      input: true,
    },
    {
      label: "About Me",
      placeholder: "Describe yourself",
      description: "go on",
      tooltip: "dont be shy",
      prefix: "just",
      suffix: "do it",
      autoExpand: false,
      tableView: true,
      key: "aboutMe",
      type: "textarea",
      input: true,
    },
    {
      label: "fav number",
      placeholder: "eg 82",
      description: "random works",
      tooltip: "any number",
      prefix: "1",
      suffix: "0",
      mask: false,
      spellcheck: true,
      tableView: false,
      delimiter: false,
      requireDecimal: false,
      inputFormat: "plain",
      key: "favNumber",
      type: "number",
      input: true,
    },
    {
      label: "Password",
      tableView: false,
      key: "password",
      type: "password",
      input: true,
      protected: true,
    },
    {
      label: "Checkbox",
      description: "fav books",
      tooltip: "select some",
      shortcut: "F",
      tableView: false,
      persistent: false,
      key: "Harry potter",
      type: "checkbox",
      input: true,
      defaultValue: true,
    },
    {
      label: "Witcher",
      tableView: false,
      key: "witcher",
      type: "checkbox",
      input: true,
      defaultValue: false,
    },
    {
      label: "Fav movies",
      optionsLabelPosition: "right",
      tableView: false,
      values: [
        {
          label: "madmax",
          value: "madmax",
          shortcut: "M",
        },
        {
          label: "casino royale",
          value: "casinoRoyale",
          shortcut: "C",
        },
        {
          label: "lotr",
          value: "lotr",
          shortcut: "L",
        },
        {
          label: "man of steel",
          value: "manOfSteel",
          shortcut: "S",
        },
      ],
      key: "favMovies",
      type: "selectboxes",
      input: true,
      inputType: "checkbox",
      defaultValue: {
        "": false,
      },
    },
    {
      label: "Sex",
      tableView: true,
      data: {
        values: [
          {
            label: "Male",
            value: "male",
          },
          {
            label: "Female",
            value: "female",
          },
          {
            label: "I dont want to disclose",
            value: "iDontWantToDisclose",
          },
        ],
      },
      selectThreshold: 0.3,
      key: "sex",
      type: "select",
      indexeddb: {
        filter: {},
      },
      input: true,
    },
    {
      label: "Click Me",
      showValidations: false,
      leftIcon: "info",
      rightIcon: "heart",
      shortcut: "J",
      tableView: false,
      key: "clickMe",
      type: "button",
      input: true,
    },
    {
      label: "User",
      optionsLabelPosition: "right",
      description: "do you use this site freq",
      tooltip: "hola?",
      inline: false,
      tableView: false,
      values: [
        {
          label: "new",
          value: "new",
          shortcut: "",
        },
        {
          label: "old",
          value: "old",
          shortcut: "",
        },
      ],
      key: "user",
      type: "radio",
      input: true,
      defaultValue: "new",
    },
    {
      type: "button",
      label: "Submit",
      key: "submit",
      disableOnInvalid: true,
      input: true,
      tableView: false,
    },
  ],
};

export const BASIC = {
  components: [
    {
      label: "First Name",
      placeholder: "eg Dragonite",
      tableView: true,
      key: "firstName",
      type: "textfield",
      input: true,
      validate: {
        required: true,
      },
    },
    {
      label: "Has a master",
      tableView: false,
      key: "hasAMaster",
      type: "checkbox",
      input: true,
      defaultValue: false,
    },
    {
      label: "About me",
      placeholder: "Describe your special abilities",
      autoExpand: false,
      tableView: true,
      key: "aboutMe",
      type: "textarea",
      input: true,
    },
    {
      label: "Age",
      placeholder: "eg: 5",
      description: "Enter your age",
      mask: false,
      spellcheck: true,
      tableView: false,
      delimiter: false,
      requireDecimal: false,
      inputFormat: "plain",
      key: "age",
      type: "number",
      input: true,
    },
    {
      label: "Gender",
      optionsLabelPosition: "right",
      inline: false,
      tableView: false,
      values: [
        {
          label: "Male",
          value: "male",
          shortcut: "",
        },
        {
          label: "Female",
          value: "female",
          shortcut: "",
        },
        {
          label: "Other",
          value: "other",
          shortcut: "",
        },
      ],
      key: "gender",
      type: "radio",
      input: true,
    },
    {
      label: "Secret Word",
      placeholder: "Enter your secret word",
      description: "we'll keep it secret",
      tableView: false,
      key: "secretWord",
      type: "password",
      input: true,
      protected: true,
    },
    {
      label: "Type",
      optionsLabelPosition: "right",
      description: "Select your ability types",
      tableView: false,
      values: [
        {
          label: "Electric",
          value: "electric",
          shortcut: "",
        },
        {
          label: "Water",
          value: "water",
          shortcut: "",
        },
        {
          label: "Fire",
          value: "fire",
          shortcut: "",
        },
        {
          label: "Grass",
          value: "grass",
          shortcut: "",
        },
        {
          label: "Rock",
          value: "rock",
          shortcut: "",
        },
      ],
      key: "type",
      type: "selectboxes",
      input: true,
      inputType: "checkbox",
      defaultValue: {
        "": false,
      },
    },
    {
      label: "House",
      placeholder: "House you belong to",
      description: "Your house",
      tableView: true,
      data: {
        values: [
          {
            label: "Red",
            value: "red",
          },
          {
            label: "Blue",
            value: "blue",
          },
          {
            label: "Green",
            value: "green",
          },
          {
            label: "Pink",
            value: "pink",
          },
          {
            label: "Black",
            value: "black",
          },
        ],
      },
      selectThreshold: 0.3,
      key: "house",
      type: "select",
      indexeddb: {
        filter: {},
      },
      input: true,
    },
    {
      label: "Reset",
      action: "reset",
      showValidations: false,
      tableView: false,
      key: "reset",
      type: "button",
      input: true,
    },
    {
      type: "button",
      label: "Submit",
      key: "submit",
      disableOnInvalid: true,
      input: true,
      tableView: false,
    },
  ],
};
