export const value0 = {
  components: [
    {
      label: "Name",
      placeholder: "your name",
      description: "Please enter your name",
      tooltip: "Seriously just put your name",
      prefix: "syl",
      suffix: "yte",
      autofocus: true,
      tableView: true,
      validate: {
        required: true,
      },
      key: "sylname",
      type: "textfield",
      input: true,
    },
    {
      label: "About Me",
      placeholder: "Describe yourself",
      description: "go on",
      tooltip: "dont be shy",
      prefix: "just",
      suffix: "do it",
      autoExpand: false,
      tableView: true,
      key: "aboutMe",
      type: "textarea",
      input: true,
    },
    {
      label: "fav number",
      placeholder: "eg 82",
      description: "random works",
      tooltip: "any number",
      prefix: "1",
      suffix: "0",
      mask: false,
      spellcheck: true,
      tableView: false,
      delimiter: false,
      requireDecimal: false,
      inputFormat: "plain",
      key: "favNumber",
      type: "number",
      input: true,
    },
    {
      label: "Password",
      tableView: false,
      key: "password",
      type: "password",
      input: true,
      protected: true,
    },
    {
      label: "Checkbox",
      description: "fav books",
      tooltip: "select some",
      shortcut: "F",
      tableView: false,
      persistent: false,
      key: "Harry potter",
      type: "checkbox",
      input: true,
      defaultValue: true,
    },
    {
      label: "Witcher",
      tableView: false,
      key: "witcher",
      type: "checkbox",
      input: true,
      defaultValue: false,
    },
    {
      label: "Fav movies",
      optionsLabelPosition: "right",
      tableView: false,
      values: [
        {
          label: "madmax",
          value: "madmax",
          shortcut: "M",
        },
        {
          label: "casino royale",
          value: "casinoRoyale",
          shortcut: "C",
        },
        {
          label: "lotr",
          value: "lotr",
          shortcut: "L",
        },
        {
          label: "man of steel",
          value: "manOfSteel",
          shortcut: "S",
        },
      ],
      key: "favMovies",
      type: "selectboxes",
      input: true,
      inputType: "checkbox",
      defaultValue: {
        "": false,
      },
    },
    {
      label: "Sex",
      tableView: true,
      data: {
        values: [
          {
            label: "Male",
            value: "male",
          },
          {
            label: "Female",
            value: "female",
          },
          {
            label: "I dont want to disclose",
            value: "iDontWantToDisclose",
          },
        ],
      },
      selectThreshold: 0.3,
      key: "sex",
      type: "select",
      indexeddb: {
        filter: {},
      },
      input: true,
    },
    {
      label: "Click Me",
      showValidations: false,
      leftIcon: "info",
      rightIcon: "heart",
      shortcut: "J",
      tableView: false,
      key: "clickMe",
      type: "button",
      input: true,
    },
    {
      label: "User",
      optionsLabelPosition: "right",
      description: "do you use this site freq",
      tooltip: "hola?",
      inline: false,
      tableView: false,
      values: [
        {
          label: "new",
          value: "new",
          shortcut: "",
        },
        {
          label: "old",
          value: "old",
          shortcut: "",
        },
      ],
      key: "user",
      type: "radio",
      input: true,
      defaultValue: "new",
    },
    {
      type: "button",
      label: "Submit",
      key: "submit",
      disableOnInvalid: true,
      input: true,
      tableView: false,
    },
  ],
};

export const value1 = {
  components: [
    {
      label: "First Name",
      placeholder: "eg Dragonite",
      tableView: true,
      key: "firstName",
      type: "textfield",
      input: true,
      validate: {
        required: true,
      },
    },
    {
      label: "Has a master",
      tableView: false,
      key: "hasAMaster",
      type: "checkbox",
      input: true,
      defaultValue: false,
    },
    {
      label: "About me",
      placeholder: "Describe your special abilities",
      autoExpand: false,
      tableView: true,
      key: "aboutMe",
      type: "textarea",
      input: true,
    },
    {
      label: "Age",
      placeholder: "eg: 5",
      description: "Enter your age",
      mask: false,
      spellcheck: true,
      tableView: false,
      delimiter: false,
      requireDecimal: false,
      inputFormat: "plain",
      key: "age",
      type: "number",
      input: true,
    },
    {
      label: "Gender",
      optionsLabelPosition: "right",
      inline: false,
      tableView: false,
      values: [
        {
          label: "Male",
          value: "male",
          shortcut: "",
        },
        {
          label: "Female",
          value: "female",
          shortcut: "",
        },
        {
          label: "Other",
          value: "other",
          shortcut: "",
        },
      ],
      key: "gender",
      type: "radio",
      input: true,
    },
    {
      label: "Secret Word",
      placeholder: "Enter your secret word",
      description: "we'll keep it secret",
      tableView: false,
      key: "secretWord",
      type: "password",
      input: true,
      protected: true,
    },
    {
      label: "Type",
      optionsLabelPosition: "right",
      description: "Select your ability types",
      tableView: false,
      values: [
        {
          label: "Electric",
          value: "electric",
          shortcut: "",
        },
        {
          label: "Water",
          value: "water",
          shortcut: "",
        },
        {
          label: "Fire",
          value: "fire",
          shortcut: "",
        },
        {
          label: "Grass",
          value: "grass",
          shortcut: "",
        },
        {
          label: "Rock",
          value: "rock",
          shortcut: "",
        },
      ],
      key: "type",
      type: "selectboxes",
      input: true,
      inputType: "checkbox",
      defaultValue: {
        "": false,
      },
    },
    {
      label: "House",
      placeholder: "House you belong to",
      description: "Your house",
      tableView: true,
      data: {
        values: [
          {
            label: "Red",
            value: "red",
          },
          {
            label: "Blue",
            value: "blue",
          },
          {
            label: "Green",
            value: "green",
          },
          {
            label: "Pink",
            value: "pink",
          },
          {
            label: "Black",
            value: "black",
          },
        ],
      },
      selectThreshold: 0.3,
      key: "house",
      type: "select",
      indexeddb: {
        filter: {},
      },
      input: true,
    },
    {
      label: "Reset",
      action: "reset",
      showValidations: false,
      tableView: false,
      key: "reset",
      type: "button",
      input: true,
    },
    {
      type: "button",
      label: "Submit",
      key: "submit",
      disableOnInvalid: true,
      input: true,
      tableView: false,
    },
  ],
};
